const PACKAGE_DATA=[{
  id:"ladakh-signature",
  title:"Ladakh Signature Journey",
  destination:"Ladakh",
  duration:7,
  category:"Mountain",
  travelType:"Couple",
  hotelCategory:"Premium",
  price:0,
  image:"https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=900&q=80",
  description:"A measured high-altitude journey through Leh, Nubra and Pangong.",
  highlights:["Leh",
  "Nubra Valley",
  "Pangong Lake"],
  inclusions:["Hotels",
  "Private transfers",
  "Sightseeing"],
  exclusions:["Flights",
  "Personal expenses"],
  itinerary:["Arrival and acclimatisation",
  "Leh sights",
  "Nubra Valley",
  "Turtuk exploration",
  "Pangong Lake",
  "Return to Leh",
  "Departure"],
  customisable:true
},
{
  id:"kashmir-premium",
  title:"Kashmir Premium Escape",
  destination:"Kashmir",
  duration:6,
  category:"Nature",
  travelType:"Family",
  hotelCategory:"Premium",
  price:0,
  image:"https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=900&q=80",
  description:"Private touring across Srinagar, Gulmarg and Pahalgam.",
  highlights:["Srinagar",
  "Gulmarg",
  "Pahalgam"],
  inclusions:["Hotels",
  "Breakfast",
  "Transfers"],
  exclusions:["Flights",
  "Optional activities"],
  itinerary:["Srinagar arrival",
  "Gulmarg",
  "Pahalgam",
  "Local touring",
  "Leisure",
  "Departure"],
  customisable:true
},
{
  id:"royal-rajasthan",
  title:"Royal Rajasthan Experience",
  destination:"Rajasthan",
  duration:8,
  category:"Heritage",
  travelType:"Luxury",
  hotelCategory:"Five-star",
  price:0,
  image:"https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80",
  description:"Heritage cities, considered pacing and distinguished stays.",
  highlights:["Jaipur",
  "Jodhpur",
  "Udaipur"],
  inclusions:["Hotels",
  "Private vehicle",
  "Guided touring"],
  exclusions:["Flights",
  "Monument fees"],
  itinerary:["Jaipur",
  "Jaipur",
  "Jodhpur",
  "Jodhpur",
  "Udaipur",
  "Udaipur",
  "Leisure",
  "Departure"],
  customisable:true
},
{
  id:"kerala-backwaters",
  title:"Kerala Backwaters and Hills",
  destination:"Kerala",
  duration:7,
  category:"Nature",
  travelType:"Couple",
  hotelCategory:"Premium",
  price:0,
  image:"https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80",
  description:"Munnar’s hills, backwaters and restorative coastal stays.",
  highlights:["Munnar",
  "Thekkady",
  "Alleppey"],
  inclusions:["Hotels",
  "Transfers",
  "Houseboat"],
  exclusions:["Flights",
  "Insurance"],
  itinerary:["Kochi",
  "Munnar",
  "Munnar",
  "Thekkady",
  "Alleppey",
  "Kovalam",
  "Departure"],
  customisable:true
},
{
  id:"himachal-family",
  title:"Himachal Family Retreat",
  destination:"Himachal Pradesh",
  duration:6,
  category:"Mountain",
  travelType:"Family",
  hotelCategory:"Comfort",
  price:0,
  image:"https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=900&q=80",
  description:"A comfortable mountain break with family-friendly planning.",
  highlights:["Shimla",
  "Manali",
  "Solang"],
  inclusions:["Hotels",
  "Vehicle",
  "Breakfast"],
  exclusions:["Flights",
  "Activities"],
  itinerary:["Shimla",
  "Shimla",
  "Manali",
  "Manali",
  "Solang",
  "Departure"],
  customisable:true
},
{
  id:"goa-luxury",
  title:"Goa Luxury Break",
  destination:"Goa",
  duration:4,
  category:"Beach",
  travelType:"Luxury",
  hotelCategory:"Five-star",
  price:0,
  image:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80",
  description:"A private coastal stay balanced between leisure and discovery.",
  highlights:["Beach resort",
  "Old Goa",
  "Private transfers"],
  inclusions:["Resort",
  "Breakfast",
  "Transfers"],
  exclusions:["Flights",
  "Meals"],
  itinerary:["Arrival",
  "Leisure",
  "Private touring",
  "Departure"],
  customisable:true
},
{
  id:"north-east",
  title:"North East Discovery",
  destination:"North East India",
  duration:8,
  category:"Adventure",
  travelType:"Group",
  hotelCategory:"Comfort",
  price:0,
  image:"https://images.unsplash.com/photo-1581791534721-e599df4417f7?auto=format&fit=crop&w=900&q=80",
  description:"A rewarding route through distinctive landscapes and communities.",
  highlights:["Shillong",
  "Cherrapunji",
  "Kaziranga"],
  inclusions:["Hotels",
  "Vehicle",
  "Touring"],
  exclusions:["Flights",
  "Camera fees"],
  itinerary:["Guwahati",
  "Shillong",
  "Cherrapunji",
  "Shillong",
  "Kaziranga",
  "Safari",
  "Guwahati",
  "Departure"],
  customisable:true
},
{
  id:"andaman-island",
  title:"Andaman Island Experience",
  destination:"Andaman",
  duration:6,
  category:"Beach",
  travelType:"Couple",
  hotelCategory:"Premium",
  price:0,
  image:"https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=900&q=80",
  description:"Island time with planned ferries, premium stays and private transfers.",
  highlights:["Port Blair",
  "Havelock",
  "Neil Island"],
  inclusions:["Hotels",
  "Ferries",
  "Transfers"],
  exclusions:["Flights",
  "Water sports"],
  itinerary:["Port Blair",
  "Havelock",
  "Havelock",
  "Neil",
  "Port Blair",
  "Departure"],
  customisable:true
}];
function packageCard(p) {
  return `<article class="package-card visible"><div class="media"><img loading="lazy" src="${p.image}" alt="${p.destination} landscape"></div><div class="card-body"><span class="badge">Customisable</span><h3>${p.title}</h3><div class="meta"><span>${p.destination}</span><span>• ${p.duration} days</span><span>• ${p.hotelCategory}</span></div><p>${p.description}</p><div class="price">Starting from ₹XX,XXX per person</div><div class="btn-row"><a class="btn ghost" href="package-details.html?id=${p.id}">View Details</a><button class="btn" data-package="${p.title}" data-modal-open="#enquiry-modal">Enquire</button></div></div></article>`
} document.addEventListener("DOMContentLoaded",
()=> {
  const grid=document.querySelector("[data-package-grid]");
  if(grid) {
    let shown=8;
    const render=()=> {
      const search=(document.querySelector("#package-search")?.value||"").toLowerCase(),
      dest=document.querySelector("#destination-filter")?.value||"",
      style=document.querySelector("#style-filter")?.value||"",
      sort=document.querySelector("#package-sort")?.value||"";
      let list=PACKAGE_DATA.filter(p=>(!search||(p.title+p.destination).toLowerCase().includes(search))&&(!dest||p.destination===dest)&&(!style||p.travelType===style));
      if(sort==="duration")list.sort((a,
      b)=>a.duration-b.duration);
      grid.innerHTML=list.slice(0,
      shown).map(packageCard).join("")||'<p class="search-empty">No packages match these filters. Try a broader search.</p>';
      grid.querySelectorAll("[data-modal-open]").forEach(b=>b.addEventListener("click",
      ()=> {
        document.querySelector('#package-name').value=b.dataset.package;
        openModal(document.querySelector("#enquiry-modal"),
        b)
      }))
    };
    document.querySelectorAll("[data-package-filter]").forEach(el=>el.addEventListener(el.tagName==="INPUT"?"input":"change",
    render));
    document.querySelector("[data-load-more]")?.addEventListener("click",
    ()=> {
      shown+=4;
      render()
    });
    render();
  } const params=new URLSearchParams(location.search),
  p=PACKAGE_DATA.find(x=>x.id===params.get("id"));
  if(p&&document.querySelector("[data-package-detail]")) {
    document.querySelector("[data-package-title]").textContent=p.title;
    document.querySelector("[data-package-description]").textContent=p.description;
    document.querySelector("[data-package-image]").src=p.image;
    document.querySelector("[data-itinerary]").innerHTML=p.itinerary.map((x,
    i)=>`<div class="accordion-item"><button class="accordion-button" aria-expanded="false">Day ${i+1}: ${x}<span>+</span></button><div class="accordion-panel"><div><p>Daily arrangements are illustrative and can be adjusted to your preferences and confirmed availability.</p></div></div></div>`).join("");
    document.querySelectorAll(".accordion-button").forEach(b=>b.onclick=()=> {
      b.closest(".accordion-item").classList.toggle("open")
    })
  }
});
